"""Extend the frequency list beyond 993 words."""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from voice_line import frequency

# Additional common English words (~1000 more)
EXTRA = [
    "able","accept","access","according","account","act","actually","admit","adopt","affect",
    "agreement","aid","air","allow","ally","alone","along","already","alter","amount",
    "animal","announce","annual","anybody","anywhere","apart","apparently","apply","argue",
    "arrange","arrest","arrive","asleep","assume","attack","attempt","attend","attitude","attorney",
    "attract","audience","automatically","aware","badly","bake","balance","ban","band","barely",
    "barrier","baseball","basic","basis","basket","bat","battle","beach","bear","beat",
    "beauty","bedroom","beer","beneath","beside","besides","bet","bible","bike","bind",
    "bird","birth","birthday","bite","blade","blame","blank","bless","blind","block",
    "bomb","bone","border","borrow","boss","bottle","bottom","bound","bowl","brain",
    "branch","brand","bread","breath","bridge","brief","briefly","bright","brilliant","broad",
    "brown","brush","budget","bug","bullet","bunch","burn","burst","bury","bus",
    "bush","busy","butter","button","cabin","cabinet","cable","cake","calm","camera",
    "camp","cap","capable","capacity","captain","capture","carbon","carefully","carrier","carrot",
    "carve","cast","castle","cat","catalog","category","cattle","caught","celebrate","celebration",
    "cellphone","chain","chairman","chamber","champion","channel","chapter","chase","cheap","cheat",
    "cheek","cheese","chest","chicken","chief","chip","chocolate","circumstance","cite","citizen",
    "civil","climb","clinic","clock","cloth","clothing","cloud","club","clue","cluster",
    "coal","coalition","coast","code","cognitive","collapse","collect","collection","colony","combat",
    "combine","comfort","comfortable","command","commander","comment","commit","committee","communicate",
    "companion","compete","complain","complete","complex","component","concentrate","concept","concern",
    "conclude","concrete","conduct","confidence","confirm","conflict","confront","confuse","connect",
    "connection","conscious","consequence","conservative","consist","consistent","constant","construct",
    "consult","consumer","consumption","contact","container","contemporary","contest","context","contract",
    "contrast","contribute","conversation","convert","convince","cook","cookie","cool","cope","copy",
    "core","corner","corporate","correct","correspond","corruption","cotton","council","counsel","count",
    "counter","county","courage","crazy","cream","crew","crisis","criteria","critic","critical",
    "criticism","crop","cross","crowd","crucial","cry","cup","curious","curtain","customer",
    "daily","damage","dance","danger","dangerous","dare","dealer","debt","deck","declare",
    "decline","deeply","deer","defend","defendant","define","definitely","definition","deliver","demand",
    "democracy","demonstrate","deny","depart","department","dependent","depict","deposit","depression",
    "derive","describe","desert","deserve","desk","desperate","destiny","destroy","detect",
    "determine","device","devote","dialogue","die","diet","differ","dig","dimension","dining",
    "direct","dirty","disability","disappear","discipline","discount","discover","discovery","dismiss",
    "disorder","display","dispute","distant","distinct","distinguish","distribute","district","disturb",
    "diverse","divide","divine","divorce","document","dollar","domestic","dominate","double","doubt",
    "dozen","draft","drag","drama","dramatic","dramatically","drink","driver","drown","drunk",
    "due","dump","dust","duty","dynamic","eager","earn","earth","ease","eastern",
    "echo","edit","edition","educate","efficiency","elderly","elect","electric","electronic",
    "element","eliminate","embrace","emerge","emergency","emission","emotion","emotional","emphasis",
    "empire","employ","enable","encounter","encourage","enemy","enforce","engage","engine",
    "engineer","enhance","enormous","ensure","enterprise","entertain","enthusiasm","entirely","entry",
    "envelope","episode","equal","equipment","equivalent","era","error","escape","especially",
    "essay","essential","establish","estate","estimate","etc","evaluate","eventually","everyday",
    "evolve","exact","examine","exceed","excellent","exception","exchange","excite","exclude",
    "exclusive","excuse","execute","exercise","exhibit","exhibition","exist","exit","expand",
    "expectation","expense","experiment","explanation","explode","exploit","explore","export","expose",
    "exposure","express","expression","extend","extension","extensive","extent","extra","extraordinary",
    "extreme","extremely","fabric","facility","factory","fade","fail","fair","fairly",
    "faith","fake","familiar","fantasy","farmer","fashion","fate","fault","favor","favorite",
    "feature","fee","feed","female","fence","fiction","fifteen","fifty","fighting","file",
    "finance","finding","firm","fishing","fitness","fix","flag","flame","flat","flee",
    "flesh","flight","float","flood","flow","flower","folk","fool","football","forever",
    "formal","formally","formation","formula","fortune","forum","foster","found","foundation","fraction",
    "fragment","framework","frankly","freeze","frequency","frequently","fresh","friday","fridge",
    "friendly","fruit","fuel","fulfill","fully","function","functional","fundamental","funeral",
    "funny","furniture","furthermore","gain","galaxy","gallery","gang","gap","garden","garlic",
    "gas","gate","gather","gay","gaze","gender","gene","generate","genetic","genius",
    "genre","gentle","gentleman","genuinely","gesture","ghost","giant","gift","glad","glance",
    "global","glory","glove","god","gold","golden","golf","govern","governor","grab",
    "grade","gradually","graduate","grain","grand","grandfather","grandmother","grant","grass","grave",
    "greatly","grocery","growing","guarantee","guard","guest","guide","guilty","guitar",
    "habitat","hall","handful","handle","happen","hardly","harm","hat","hate","heal",
    "healthy","hearing","heaven","heavily","height","helicopter","hell","helpful","hence",
    "heritage","hero","hesitate","hide","highlight","highly","highway","hill","hint",
    "hip","hire","historian","historic","holy","homework","honest","honor","hook",
    "horizon","horror","host","hostile","household","housing","humor","hunger","hunter","hurt",
    "hypothesis","ice","ideal","identity","ideological","ignore","illegal","illness","illustrate",
    "imagination","immediate","immigrant","immigration","implement","implication","imply","import","importance",
    "impose","impossible","impress","impression","impressive","incident","income","incorporate","increasingly",
    "incredible","independence","independent","indication","indicator","industrial","inevitable","infant",
    "infection","inflation","influence","inform","ingredient","initial","initially","initiative","injury",
    "inner","innocent","innovation","input","inquiry","insist","inspection","inspector","install",
    "instance","institutional","instrument","insurance","intellectual","intelligence","intend","intense",
    "intention","interaction","internal","interpret","intervention","introduce","invasion","invent",
    "investigate","investigation","investor","invite","iron","ironically","island","isolate",
    "jacket","jail","jet","jewish","joint","journal","journalist","journey","joy","judge",
    "judgment","juice","jump","junior","jury","justice","justify","killer","killing","king",
    "kiss","kitchen","knee","knife","knock","label","labor","laboratory","lack","lake",
    "lamp","landscape","lap","largely","laser","latter","laugh","launch","leather","lecture",
    "legacy","legend","legislation","legislative","lemon","length","lens","lesson","liberal",
    "liberty","license","lifestyle","lifetime","lighting","likely","limit","limitation","link",
    "lip","literary","literature","load","loan","lobby","locate","location","lock","log",
    "logic","lonely","loose","lord","loud","lover","loyal","luck","lunch","lung",
    "machine","mad","magic","maintain","maker","male","mall","manufacturer","manufacturing","march",
    "margin","mark","marketing","mass","massive","master","match","mate","math","maximum",
    "mayor","meaning","meanwhile","measurement","mechanism","medal","medium","membership","mental",
    "mentally","mention","mentor","menu","merchant","mere","merely","mess","metal","meter",
    "mexican","middle","midnight","migration","mild","milk","mill","minor","minority","miracle",
    "mirror","missile","missing","mistake","mix","mixture","mobility","moderate","modest","molecule",
    "mom","monday","monitor","monster","mood","moon","moral","moreover","mortgage","mostly",
    "motor","mount","mountain","mouse","mud","multiple","murder","muscle","museum","mushroom",
    "muslim","mutual","mystery","myth","naive","narrow","nasty","native","nato","navy",
    "neat","necessarily","negotiate","neighbor","nerve","nervous","nest","net","neutral","nevertheless",
    "nightmare","nobody","noise","nominate","nonprofit","noon","normal","normally","nose","notably",
    "notion","novel","nowhere","nuclear","numerous","nurse","nut","objective","obligation","observation",
    "observe","observer","obstacle","obtain","obvious","obviously","occasion","occasionally","occupy",
    "ocean","odd","offender","offensive","ongoing","online","opening","opera","operate",
    "operator","opinion","opponent","oppose","opposite","opposition","option","orange","ordinary",
    "organ","organic","organize","orientation","origin","original","originally","ought","outcome",
    "outline","output","overcome","overlook","overwhelm","owe","oxygen","pace","pack","package",
    "paint","painting","pale","pan","panel","panic","pant","paragraph","parallel","parent",
    "park","parking","participant","particle","partly","passage","passenger","passion","passive","path",
    "patient","pause","peak","peer","penalty","pension","pepper","perceive","percentage","perception",
    "perfect","perfectly","personality","personally","personnel","perspective","persuade","pet","phase",
    "phenomenon","philosophy","phrase","physically","physician","piano","pile","pilot","pine","pink",
    "pipe","pitch","pizza","planet","plastic","plate","platform","pleasant","pleasure","plenty",
    "plot","plus","pocket","poem","poet","poetry","pole","poll","pollution","pool",
    "pop","portion","portrait","portray","pose","possess","possession","possibly","pot","potential",
    "potentially","pour","poverty","powder","prayer","precious","precise","precisely","predict","prefer",
    "pregnancy","pregnant","preliminary","premise","premium","preparation","prescription","presence",
    "preserve","presidential","press","presumably","pretend","prevail","prevent","previous","previously",
    "pride","priest","primarily","primary","prime","principal","principle","print","prior",
    "priority","prison","prisoner","privacy","privilege","prize","pro","proceed","producer",
    "profile","profit","profound","prominent","promise","promising","prompt","proof","proper",
    "properly","proportion","propose","prosecutor","prospect","prosperity","protein","protest","province",
    "provision","psychological","psychologist","publication","publisher","pulse","pump","purchase",
    "pure","purple","pursue","puzzle","qualify","quarter","quarterback","queen","quiet",
    "quit","racial","racism","radical","rain","rank","rapid","rapidly","rare","rarely",
    "rating","ratio","raw","react","reaction","reader","reading","realistic","realm","rear",
    "reasonable","rebel","recall","recession","recipe","recognition","recommend","recover","recovery",
    "recruit","refer","reference","reflection","reform","refugee","refuse","regard","regarding",
    "regardless","regime","region","regional","register","regulate","regulation","reject","relate",
    "relative","release","relevant","relief","religion","rely","remarkable","remedy","remote",
    "render","repeatedly","replace","reporter","representative","republic","reputation","request",
    "resemble","reservation","reserve","resident","resign","resist","resistance","resolution","resolve",
    "resort","respective","restore","restriction","retain","retire","retirement","retreat","revenue",
    "review","revolution","rhythm","rice","ride","rifle","ring","riot","rise","risky",
    "ritual","rival","river","rob","robot","roll","romantic","roof","root","rope",
    "rough","roughly","round","route","routine","royal","rub","ruin","rumor","running",
    "rural","rush","safety","sake","salad","salary","sale","salt","sample","sanction",
    "sand","satellite","satisfaction","satisfy","sauce","scale","scandal","scare","scenario","schedule",
    "scholar","scholarship","scope","score","scratch","scream","screen","script","seal","secret",
    "secretary","sector","secure","seed","select","selection","self","senator","senior","sensitive",
    "sentence","separate","separation","sequence","serve","settle","settlement","severe","sexually",
    "shade","shadow","shame","shape","shift","shine","ship","shock","shopping","shore",
    "shortly","shut","sibling","sight","signal","signature","significantly","silence","silly",
    "silver","similarly","sin","sink","sir","ski","slave","sleep","slice","slide",
    "slight","slightly","slip","slope","slow","smart","smell","smile","smoke","snap",
    "snow","soak","soccer","socially","solar","solely","solid","solution","somehow","soul",
    "span","spare","speaker","species","specifically","spectrum","speech","spell","spend","spin",
    "spirit","spiritual","split","spokesman","sponsor","spot","spread","square","squeeze","stable",
    "stadium","stake","stance","stare","statistics","steal","steel","stem","stick","stomach",
    "storage","storm","straight","strain","strange","strategic","straw","stream","strength","stretch",
    "strict","strike","string","strip","stroke","strongly","studio","submit","subsequent","subsidy",
    "substance","substantial","substitute","succeed","succumb","sufficient","sugar","suicide","suit",
    "summary","summit","sun","super","superior","supply","suppose","supposed","supreme","surely",
    "surface","surgeon","surplus","surprisingly","surround","surveillance","survey","survival","survivor",
    "suspect","suspend","sustain","swear","sweep","sweet","swim","swing","switch","symbol",
    "symptom","syndrome","tactic","tail","tale","talent","tank","tap","tape","target",
    "taste","tea","technical","teen","teenage","telephone","telescope","temporary","tenant","tendency",
    "tension","tent","terrain","terrible","territory","terror","terrorist","text","texture","thanks",
    "theme","theology","theoretical","therapy","thick","thin","thoroughly","thoughtful","threaten","throat",
    "throw","thumb","ticket","tie","tight","timing","tiny","tip","tire","tissue",
    "title","tobacco","toe","tolerance","tolerate","toll","tone","tongue","tool","tooth",
    "topic","toss","totally","tour","tourist","tournament","toward","tower","toxic","trace",
    "track","tradition","traffic","tragedy","trail","train","trait","transaction","transfer","transform",
    "transition","transportation","trap","treasure","treaty","tremendous","trend","tribe","trick","trigger",
    "troop","tropical","truck","truly","trust","tube","tune","tunnel","twist","ultimately",
    "unable","uncertain","uncle","uncomfortable","undergo","undermine","unemployment","unexpected","unfair",
    "unfold","unfortunately","unhappy","uniform","union","unique","unity","universal","universe",
    "unknown","unlike","unlikely","unprecedented","upgrade","urban","urge","useful","user","usual",
    "utility","vacation","vaccine","valid","valley","valuable","van","variable","variation","variety",
    "vegetable","vehicle","venture","venue","verbal","verdict","verse","version","vessel","veteran",
    "via","victory","video","viewer","village","violate","violation","virtually","virtue","visible",
    "vision","visual","vital","voice","volume","voluntary","volunteer","voter","vulnerable","wage",
    "wake","wander","warning","warrior","wash","waste","wave","weak","wealth","wealthy",
    "weather","website","wedding","weekend","weekly","welcome","welfare","western","whereas","whisper",
    "wild","wildlife","willing","wind","wine","wing","winner","winter","wipe","wire",
    "wisdom","wise","withdraw","witness","wonderful","wood","wooden","workforce","workout","workshop",
    "worship","worth","wound","wrap","yard","yeah","yell","yesterday","yield","zone"
]

existing = set(frequency.FREQUENCY_LIST)
new_words = [w for w in EXTRA if w not in existing]
print(f"Adding {len(new_words)} new words")
print(f"Total will be: {len(existing) + len(new_words)}")

# Write the expanded list
out_path = Path(__file__).parent.parent / "src" / "voice_line" / "frequency.py"
with open(out_path, "w") as f:
    f.write('"""\nEnglish word frequency list.\nTop ~2000 words, sorted most common first.\n"""\n\n')
    f.write("FREQUENCY_LIST: list[str] = [\n")
    all_words = frequency.FREQUENCY_LIST + sorted(new_words)
    for i in range(0, len(all_words), 10):
        batch = all_words[i:i+10]
        line = "    " + ", ".join(f'"{w}"' for w in batch)
        if i + 10 < len(all_words):
            line += ","
        f.write(line + "\n")
    f.write("]\n")
    f.write(f"# {len(all_words)} total words\n")

print(f"Wrote {len(all_words)} words to frequency.py")
